FROM node:20-alpine
WORKDIR /usr/local/app

RUN npm install -g pnpm

WORKDIR /usr/local/app/frontend

COPY ./frontend/package.json ./
COPY ./backend/tsconfig*.json ./

WORKDIR /usr/local/app
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
RUN pnpm install -r

WORKDIR /usr/local/app/frontend
COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]